### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by Shuunen** [CharlGottschalk/coppersmith#1]
Hi,

I wanted to try the lib but can't pass the npm install step :face_with_head_bandage: 

https://gist.github.com/Shuunen/0f62b15536b30d49fdd7429b239ce9e5

Env : 
Windows 7 64bit
Node 6.7.0
Npm 3.10.3

**Comment by CharlGottschalk** [comment]
Hi @Shuunen 

I tested the install on a few machines and can't seem to reproduce the error as it installs fine.

Would you mind running the command `npm install -g coppersmith` and letting me know the result?

**Comment by dcarrask** [comment]
Hi @CharlGottschalk !

I wanted to test your work and I couldn't. I let you know I work daily with node projects and I have no problems.

Env: OS X 10.12

```
sudo npm install -g coppersmith

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/coppersmith/node_modules/metalsmith-layouts
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/coppersmith
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/coppersmith/node_modules
/usr/local/lib
└─┬ coppersmith@1.1.1
  └── metalsmith-layouts@1.6.5  (git://github.com/superwolff/metalsmith-layouts.git#4002b654be2264cba92e6b9aa635d7fce192740b)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "coppersmith"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! path /usr/local/lib/node_modules/coppersmith/node_modules/metalsmith-layouts
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/coppersmith/node_modules/metalsmith-layouts'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/coppersmith/node_modules/metalsmith-layouts']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/coppersmith/node_modules/metalsmith-layouts' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/diego/__work/__temp/coopermith/npm-debug.log
 ✘ diego@macbook  ~/__work/__temp/coopermith  sudo npm install -g coppersmith
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:523:7)
    at onSocketNT (_http_client.js:535:5)
/usr/local/bin/copper -> /usr/local/lib/node_modules/coppersmith/cs/cmd/index.js
/usr/local/lib
└─┬ coppersmith@1.1.1
  └── metalsmith-layouts@1.6.5  (git://github.com/superwolff/metalsmith-layouts.git#4002b654be2264cba92e6b9aa635d7fce192740b)
```

After I try to execute and:

```
copper init

env: node\r: No such file or directory
```

I'll be pleased to read your suggestion for testing your module.

Thanks!

**Comment by dfross** [comment]
I too am having issues installing (win10, 64, node 6.9.0). I get the same error as @Shuunen and tried your suggestion of installing globally then running `copper init` within my project folder with the following error:
```
copper init
module.js:471
    throw err;
    ^

  [0m[97m[41mError[0m[90m:[0m[37m [0m[97mCannot find module 'C:\GitHub\coppersmith-test\package.json'[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m469[0m[37m [0m[37mFunction.Module._resolveFilename[0m
[0m  [0m  [0m[90mmodule.js:469:15[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m417[0m[37m [0m[37mFunction.Module._load[0m
[0m  [0m  [0m[90mmodule.js:417:25[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m497[0m[37m [0m[37mModule.require[0m
[0m  [0m  [0m[90mmodule.js:497:17[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m20[0m[37m [0m[37mrequire[0m
[0m  [0m  [0m[90minternal/module.js:20:19[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93minit.js[0m[90m:[0m[93m10[0m[37m [0m[37mObject.<anonymous>[0m
[0m  [0m  [0m[90m[npm]/[coppersmith]/cs/cmd/init.js:10:8[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m570[0m[37m [0m[37mModule._compile[0m
[0m  [0m  [0m[90mmodule.js:570:32[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m579[0m[37m [0m[37mObject.Module._extensions..js[0m
[0m  [0m  [0m[90mmodule.js:579:10[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m487[0m[37m [0m[37mModule.load[0m
[0m  [0m  [0m[90mmodule.js:487:32[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m446[0m[37m [0m[37mtryModuleLoad[0m
[0m  [0m  [0m[90mmodule.js:446:12[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mmodule.js[0m[90m:[0m[93m438[0m[37m [0m[37mFunction.Module._load[0m
[0m  [0m  [0m[90mmodule.js:438:3[0m
[0m  [0m
[0m
```

**Comment by CharlGottschalk** [comment]
Hi @dcarrask, @dfross 

Thanks for logging the issues.

It looks like your errors are due to a `package.json` not existing in your project directories.

CopperSmith loads the `package.json` file to retrieve the `author` property.

Please run `npm init` in your project root to create the `package.json` file and try the `copper init` command again.

Please let me know of the result.

I will make the appropriate changes to ignore the import if it doesn't exist.

**Comment by CharlGottschalk** [comment]
Hi @Shuunen

From your [gist](https://gist.github.com/Shuunen/0f62b15536b30d49fdd7429b239ce9e5) it looks like the installation error occured due to a failed connection to github.

> Line 1901: 741 verbose stack fatal: unable to connect to github.com

One of the dependencies gets installed directly from github, due to the npm version breaking CopperSmith. (Waiting for a working version)

Please make sure you can connect to github.com and try the installation again.

Please let me know of the result.

**Comment by dfross** [comment]
@CharlGottschalk 

I installed globally, ran `npm init` and filled it all out, then attempted `copper init` and it closed my cmd window entirely. Attempted to do a simple version check of copper, `copper -v` and it closed the cmd window again.

**Comment by CharlGottschalk** [comment]
@dfross 

Thanks for your patience.

I know you must be fed up by now, but could you please remove CopperSmith completely using `npm remove -g coppersmith` and `npm remove --save coppersmith` from your `coppersmith-test` project, then re-install using `npm install -g coppersmith`.

I updated the package and fixed the commands which never handled `-v`.

**Comment by dfross** [comment]
Thank you @CharlGottschalk! I got it installed now and working great.

**Comment by CharlGottschalk** [comment]
@dfross 

Awesome! Glad to hear that. 

I hope it will serve you well.

Thanks again for your patience.
